// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using ZtherApiIntegration.API.Models;

namespace ZtherApiIntegration.API
{
    public partial interface IGroupOrders
    {
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='model'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> CreateWithOperationResponseAsync(string brand, GroupOrder model, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<GroupOrderList>> GetAllGroupOrdersWithOperationResponseAsync(string brand, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IndustryList>> GetAllIndustryByBrandWithOperationResponseAsync(string brand, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<OutfittedList>> GetAllNumberToBeOutfittedByBrandWithOperationResponseAsync(string brand, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<GroupOrder>> GetGroupOrderByIdWithOperationResponseAsync(string brand, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> RemoveSignUpsWithOperationResponseAsync(string brand, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
