// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;

namespace ZtherApiIntegration.API
{
    public partial interface IImages
    {
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetCatalogBannerImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetCatalogImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetCollectionImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetDetailImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetLogoImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetPrintBannerImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetPrintImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetSeasonalImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetSliderImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetThumbnailImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetTileImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='filename'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> GetZoomImageWithOperationResponseAsync(string filename, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
