// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using ZtherApiIntegration.API.Models;

namespace ZtherApiIntegration.API
{
    public partial interface ISeoOperations
    {
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='pagename'>
        /// Required.
        /// </param>
        /// <param name='productCode'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Seo>> GetByBrandAndPageNameWithOperationResponseAsync(string brand, string pagename, string productCode = null, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
