// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using ZtherApiIntegration.API.Models;

namespace ZtherApiIntegration.API
{
    public partial interface ISignUps
    {
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='model'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> CreateSignUpsWithOperationResponseAsync(string brand, SignUp model, CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='model'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> CreateSignUpsInSalesforceResponseAsync(string brand, SignUp model, CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<SignUpList>> GetAllSignUpsWithOperationResponseAsync(string brand, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<SignUp>> GetSignUpsByIdWithOperationResponseAsync(string brand, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> RemoveSignUpsWithOperationResponseAsync(string brand, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
