// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using ZtherApiIntegration.API;
using ZtherApiIntegration.API.Models;

namespace ZtherApiIntegration.API
{
    public static partial class SeoOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the ZtherApiIntegration.API.ISeoOperations.
        /// </param>
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='pagename'>
        /// Required.
        /// </param>
        /// <param name='productCode'>
        /// Optional.
        /// </param>
        public static Seo GetByBrandAndPageName(this ISeoOperations operations, string brand, string pagename, string productCode = null)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ISeoOperations)s).GetByBrandAndPageNameAsync(brand, pagename, productCode);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ZtherApiIntegration.API.ISeoOperations.
        /// </param>
        /// <param name='brand'>
        /// Required.
        /// </param>
        /// <param name='pagename'>
        /// Required.
        /// </param>
        /// <param name='productCode'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Seo> GetByBrandAndPageNameAsync(this ISeoOperations operations, string brand, string pagename, string productCode = null, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<ZtherApiIntegration.API.Models.Seo> result = await operations.GetByBrandAndPageNameWithOperationResponseAsync(brand, pagename, productCode, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
