// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ZtherApiIntegration.API.Models
{
    public partial class Breadcrumb
    {
        private string _category;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Category
        {
            get { return this._category; }
            set { this._category = value; }
        }
        
        private string _collection;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Collection
        {
            get { return this._collection; }
            set { this._collection = value; }
        }
        
        private string _gender;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Gender
        {
            get { return this._gender; }
            set { this._gender = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Breadcrumb class.
        /// </summary>
        public Breadcrumb()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken categoryValue = inputObject["category"];
                if (categoryValue != null && categoryValue.Type != JTokenType.Null)
                {
                    this.Category = ((string)categoryValue);
                }
                JToken collectionValue = inputObject["collection"];
                if (collectionValue != null && collectionValue.Type != JTokenType.Null)
                {
                    this.Collection = ((string)collectionValue);
                }
                JToken genderValue = inputObject["gender"];
                if (genderValue != null && genderValue.Type != JTokenType.Null)
                {
                    this.Gender = ((string)genderValue);
                }
            }
        }
    }
}
