// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ZtherApiIntegration.API.Models
{
    public partial class Category
    {
        private bool? _display;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Display
        {
            get { return this._display; }
            set { this._display = value; }
        }
        
        private string _key;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Key
        {
            get { return this._key; }
            set { this._key = value; }
        }
        
        private string _value;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Value
        {
            get { return this._value; }
            set { this._value = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Category class.
        /// </summary>
        public Category()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken displayValue = inputObject["display"];
                if (displayValue != null && displayValue.Type != JTokenType.Null)
                {
                    this.Display = ((bool)displayValue);
                }
                JToken keyValue = inputObject["key"];
                if (keyValue != null && keyValue.Type != JTokenType.Null)
                {
                    this.Key = ((string)keyValue);
                }
                JToken valueValue = inputObject["value"];
                if (valueValue != null && valueValue.Type != JTokenType.Null)
                {
                    this.Value = ((string)valueValue);
                }
            }
        }
    }
}
