// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ZtherApiIntegration.API.Models
{
    public partial class ColorUpdate
    {
        private string _colorCode;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string ColorCode
        {
            get { return this._colorCode; }
            set { this._colorCode = value; }
        }
        
        private string _displayName;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string DisplayName
        {
            get { return this._displayName; }
            set { this._displayName = value; }
        }
        
        private bool? _isNew;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsNew
        {
            get { return this._isNew; }
            set { this._isNew = value; }
        }
        
        private bool? _isPopular;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsPopular
        {
            get { return this._isPopular; }
            set { this._isPopular = value; }
        }
        
        private string _primaryHex;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PrimaryHex
        {
            get { return this._primaryHex; }
            set { this._primaryHex = value; }
        }
        
        private string _printGroup;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string PrintGroup
        {
            get { return this._printGroup; }
            set { this._printGroup = value; }
        }
        
        private string _secondaryHex;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SecondaryHex
        {
            get { return this._secondaryHex; }
            set { this._secondaryHex = value; }
        }
        
        private int? _sortOrder;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? SortOrder
        {
            get { return this._sortOrder; }
            set { this._sortOrder = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ColorUpdate class.
        /// </summary>
        public ColorUpdate()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the ColorUpdate class with required
        /// arguments.
        /// </summary>
        public ColorUpdate(string colorCode, string printGroup, string displayName)
            : this()
        {
            if (colorCode == null)
            {
                throw new ArgumentNullException("colorCode");
            }
            if (printGroup == null)
            {
                throw new ArgumentNullException("printGroup");
            }
            if (displayName == null)
            {
                throw new ArgumentNullException("displayName");
            }
            this.ColorCode = colorCode;
            this.PrintGroup = printGroup;
            this.DisplayName = displayName;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ColorUpdate
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.ColorCode == null)
            {
                throw new ArgumentNullException("ColorCode");
            }
            if (this.DisplayName == null)
            {
                throw new ArgumentNullException("DisplayName");
            }
            if (this.PrintGroup == null)
            {
                throw new ArgumentNullException("PrintGroup");
            }
            if (this.ColorCode != null)
            {
                outputObject["colorCode"] = this.ColorCode;
            }
            if (this.DisplayName != null)
            {
                outputObject["displayName"] = this.DisplayName;
            }
            if (this.IsNew != null)
            {
                outputObject["isNew"] = this.IsNew.Value;
            }
            if (this.IsPopular != null)
            {
                outputObject["isPopular"] = this.IsPopular.Value;
            }
            if (this.PrimaryHex != null)
            {
                outputObject["primaryHex"] = this.PrimaryHex;
            }
            if (this.PrintGroup != null)
            {
                outputObject["printGroup"] = this.PrintGroup;
            }
            if (this.SecondaryHex != null)
            {
                outputObject["secondaryHex"] = this.SecondaryHex;
            }
            if (this.SortOrder != null)
            {
                outputObject["sortOrder"] = this.SortOrder.Value;
            }
            return outputObject;
        }
    }
}
