// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ZtherApiIntegration.API.Models
{
    public partial class Color
    {
        private string _colorCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ColorCode
        {
            get { return this._colorCode; }
            set { this._colorCode = value; }
        }
        
        private string _colorName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ColorName
        {
            get { return this._colorName; }
            set { this._colorName = value; }
        }
        
        private string _displayName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string DisplayName
        {
            get { return this._displayName; }
            set { this._displayName = value; }
        }
        
        private bool? _isNew;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsNew
        {
            get { return this._isNew; }
            set { this._isNew = value; }
        }
        
        private bool? _isPopular;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsPopular
        {
            get { return this._isPopular; }
            set { this._isPopular = value; }
        }
        
        private string _primaryHex;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PrimaryHex
        {
            get { return this._primaryHex; }
            set { this._primaryHex = value; }
        }
        
        private string _printImageName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PrintImageName
        {
            get { return this._printImageName; }
            set { this._printImageName = value; }
        }
        
        private string _printImageUri;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PrintImageUri
        {
            get { return this._printImageUri; }
            set { this._printImageUri = value; }
        }
        
        private string _secondaryHex;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SecondaryHex
        {
            get { return this._secondaryHex; }
            set { this._secondaryHex = value; }
        }
        
        private string _swatchType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SwatchType
        {
            get { return this._swatchType; }
            set { this._swatchType = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Color class.
        /// </summary>
        public Color()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken colorCodeValue = inputObject["colorCode"];
                if (colorCodeValue != null && colorCodeValue.Type != JTokenType.Null)
                {
                    this.ColorCode = ((string)colorCodeValue);
                }
                JToken colorNameValue = inputObject["colorName"];
                if (colorNameValue != null && colorNameValue.Type != JTokenType.Null)
                {
                    this.ColorName = ((string)colorNameValue);
                }
                JToken displayNameValue = inputObject["displayName"];
                if (displayNameValue != null && displayNameValue.Type != JTokenType.Null)
                {
                    this.DisplayName = ((string)displayNameValue);
                }
                JToken isNewValue = inputObject["isNew"];
                if (isNewValue != null && isNewValue.Type != JTokenType.Null)
                {
                    this.IsNew = ((bool)isNewValue);
                }
                JToken isPopularValue = inputObject["isPopular"];
                if (isPopularValue != null && isPopularValue.Type != JTokenType.Null)
                {
                    this.IsPopular = ((bool)isPopularValue);
                }
                JToken primaryHexValue = inputObject["primaryHex"];
                if (primaryHexValue != null && primaryHexValue.Type != JTokenType.Null)
                {
                    this.PrimaryHex = ((string)primaryHexValue);
                }
                JToken printImageNameValue = inputObject["printImageName"];
                if (printImageNameValue != null && printImageNameValue.Type != JTokenType.Null)
                {
                    this.PrintImageName = ((string)printImageNameValue);
                }
                JToken printImageUriValue = inputObject["printImageUri"];
                if (printImageUriValue != null && printImageUriValue.Type != JTokenType.Null)
                {
                    this.PrintImageUri = ((string)printImageUriValue);
                }
                JToken secondaryHexValue = inputObject["secondaryHex"];
                if (secondaryHexValue != null && secondaryHexValue.Type != JTokenType.Null)
                {
                    this.SecondaryHex = ((string)secondaryHexValue);
                }
                JToken swatchTypeValue = inputObject["swatchType"];
                if (swatchTypeValue != null && swatchTypeValue.Type != JTokenType.Null)
                {
                    this.SwatchType = ((string)swatchTypeValue);
                }
            }
        }
    }
}
