// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ZtherApiIntegration.API.Models
{
    public partial class Image
    {
        private string _catalogImageUri;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CatalogImageUri
        {
            get { return this._catalogImageUri; }
            set { this._catalogImageUri = value; }
        }
        
        private string _collectionImageUri;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CollectionImageUri
        {
            get { return this._collectionImageUri; }
            set { this._collectionImageUri = value; }
        }
        
        private string _colorCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ColorCode
        {
            get { return this._colorCode; }
            set { this._colorCode = value; }
        }
        
        private string _detailImageUri;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string DetailImageUri
        {
            get { return this._detailImageUri; }
            set { this._detailImageUri = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ID
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _imageName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ImageName
        {
            get { return this._imageName; }
            set { this._imageName = value; }
        }
        
        private bool? _is360Display;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Is360Display
        {
            get { return this._is360Display; }
            set { this._is360Display = value; }
        }
        
        private bool? _isLineArt;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsLineArt
        {
            get { return this._isLineArt; }
            set { this._isLineArt = value; }
        }
        
        private bool? _isPrimary;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsPrimary
        {
            get { return this._isPrimary; }
            set { this._isPrimary = value; }
        }
        
        private DateTimeOffset? _lastResizeDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? LastResizeDate
        {
            get { return this._lastResizeDate; }
            set { this._lastResizeDate = value; }
        }
        
        private string _productCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ProductCode
        {
            get { return this._productCode; }
            set { this._productCode = value; }
        }
        
        private bool? _resize;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Resize
        {
            get { return this._resize; }
            set { this._resize = value; }
        }
        
        private int? _sortOrder;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? SortOrder
        {
            get { return this._sortOrder; }
            set { this._sortOrder = value; }
        }
        
        private string _thumbnailImageUri;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ThumbnailImageUri
        {
            get { return this._thumbnailImageUri; }
            set { this._thumbnailImageUri = value; }
        }
        
        private string _zoomImageUri;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ZoomImageUri
        {
            get { return this._zoomImageUri; }
            set { this._zoomImageUri = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Image class.
        /// </summary>
        public Image()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken catalogImageUriValue = inputObject["catalogImageUri"];
                if (catalogImageUriValue != null && catalogImageUriValue.Type != JTokenType.Null)
                {
                    this.CatalogImageUri = ((string)catalogImageUriValue);
                }
                JToken collectionImageUriValue = inputObject["collectionImageUri"];
                if (collectionImageUriValue != null && collectionImageUriValue.Type != JTokenType.Null)
                {
                    this.CollectionImageUri = ((string)collectionImageUriValue);
                }
                JToken colorCodeValue = inputObject["colorCode"];
                if (colorCodeValue != null && colorCodeValue.Type != JTokenType.Null)
                {
                    this.ColorCode = ((string)colorCodeValue);
                }
                JToken detailImageUriValue = inputObject["detailImageUri"];
                if (detailImageUriValue != null && detailImageUriValue.Type != JTokenType.Null)
                {
                    this.DetailImageUri = ((string)detailImageUriValue);
                }
                JToken idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.ID = ((int)idValue);
                }
                JToken imageNameValue = inputObject["imageName"];
                if (imageNameValue != null && imageNameValue.Type != JTokenType.Null)
                {
                    this.ImageName = ((string)imageNameValue);
                }
                JToken is360DisplayValue = inputObject["is360Display"];
                if (is360DisplayValue != null && is360DisplayValue.Type != JTokenType.Null)
                {
                    this.Is360Display = ((bool)is360DisplayValue);
                }
                JToken isLineArtValue = inputObject["isLineArt"];
                if (isLineArtValue != null && isLineArtValue.Type != JTokenType.Null)
                {
                    this.IsLineArt = ((bool)isLineArtValue);
                }
                JToken isPrimaryValue = inputObject["isPrimary"];
                if (isPrimaryValue != null && isPrimaryValue.Type != JTokenType.Null)
                {
                    this.IsPrimary = ((bool)isPrimaryValue);
                }
                JToken lastResizeDateValue = inputObject["lastResizeDate"];
                if (lastResizeDateValue != null && lastResizeDateValue.Type != JTokenType.Null)
                {
                    this.LastResizeDate = ((DateTimeOffset)lastResizeDateValue);
                }
                JToken productCodeValue = inputObject["productCode"];
                if (productCodeValue != null && productCodeValue.Type != JTokenType.Null)
                {
                    this.ProductCode = ((string)productCodeValue);
                }
                JToken resizeValue = inputObject["resize"];
                if (resizeValue != null && resizeValue.Type != JTokenType.Null)
                {
                    this.Resize = ((bool)resizeValue);
                }
                JToken sortOrderValue = inputObject["sortOrder"];
                if (sortOrderValue != null && sortOrderValue.Type != JTokenType.Null)
                {
                    this.SortOrder = ((int)sortOrderValue);
                }
                JToken thumbnailImageUriValue = inputObject["thumbnailImageUri"];
                if (thumbnailImageUriValue != null && thumbnailImageUriValue.Type != JTokenType.Null)
                {
                    this.ThumbnailImageUri = ((string)thumbnailImageUriValue);
                }
                JToken zoomImageUriValue = inputObject["zoomImageUri"];
                if (zoomImageUriValue != null && zoomImageUriValue.Type != JTokenType.Null)
                {
                    this.ZoomImageUri = ((string)zoomImageUriValue);
                }
            }
        }
    }
}
