// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ZtherApiIntegration.API.Models
{
    public partial class Pagination
    {
        private int? _currentPage;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CurrentPage
        {
            get { return this._currentPage; }
            set { this._currentPage = value; }
        }
        
        private string _nextPage;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string NextPage
        {
            get { return this._nextPage; }
            set { this._nextPage = value; }
        }
        
        private int? _pageSize;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? PageSize
        {
            get { return this._pageSize; }
            set { this._pageSize = value; }
        }
        
        private string _previousPage;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PreviousPage
        {
            get { return this._previousPage; }
            set { this._previousPage = value; }
        }
        
        private int? _totalCount;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? TotalCount
        {
            get { return this._totalCount; }
            set { this._totalCount = value; }
        }
        
        private int? _totalPages;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? TotalPages
        {
            get { return this._totalPages; }
            set { this._totalPages = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Pagination class.
        /// </summary>
        public Pagination()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken currentPageValue = inputObject["currentPage"];
                if (currentPageValue != null && currentPageValue.Type != JTokenType.Null)
                {
                    this.CurrentPage = ((int)currentPageValue);
                }
                JToken nextPageValue = inputObject["nextPage"];
                if (nextPageValue != null && nextPageValue.Type != JTokenType.Null)
                {
                    this.NextPage = ((string)nextPageValue);
                }
                JToken pageSizeValue = inputObject["pageSize"];
                if (pageSizeValue != null && pageSizeValue.Type != JTokenType.Null)
                {
                    this.PageSize = ((int)pageSizeValue);
                }
                JToken previousPageValue = inputObject["previousPage"];
                if (previousPageValue != null && previousPageValue.Type != JTokenType.Null)
                {
                    this.PreviousPage = ((string)previousPageValue);
                }
                JToken totalCountValue = inputObject["totalCount"];
                if (totalCountValue != null && totalCountValue.Type != JTokenType.Null)
                {
                    this.TotalCount = ((int)totalCountValue);
                }
                JToken totalPagesValue = inputObject["totalPages"];
                if (totalPagesValue != null && totalPagesValue.Type != JTokenType.Null)
                {
                    this.TotalPages = ((int)totalPagesValue);
                }
            }
        }
    }
}
