// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;
using ZtherApiIntegration.API.Models;

namespace ZtherApiIntegration.API.Models
{
    public partial class ProductLineArtList
    {
        private int? _count;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Count
        {
            get { return this._count; }
            set { this._count = value; }
        }
        
        private IList<ProductLineArt> _results;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ProductLineArt> Results
        {
            get { return this._results; }
            set { this._results = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ProductLineArtList class.
        /// </summary>
        public ProductLineArtList()
        {
            this.Results = new LazyList<ProductLineArt>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken countValue = inputObject["count"];
                if (countValue != null && countValue.Type != JTokenType.Null)
                {
                    this.Count = ((int)countValue);
                }
                JToken resultsSequence = ((JToken)inputObject["results"]);
                if (resultsSequence != null && resultsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken resultsValue in ((JArray)resultsSequence))
                    {
                        ProductLineArt productLineArt = new ProductLineArt();
                        productLineArt.DeserializeJson(resultsValue);
                        this.Results.Add(productLineArt);
                    }
                }
            }
        }
    }
}
