// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;
using ZtherApiIntegration.API.Models;

namespace ZtherApiIntegration.API.Models
{
    public partial class ProductReviewList
    {
        private double? _average;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? Average
        {
            get { return this._average; }
            set { this._average = value; }
        }
        
        private int? _count;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Count
        {
            get { return this._count; }
            set { this._count = value; }
        }
        
        private Pagination _pagination;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Pagination Pagination
        {
            get { return this._pagination; }
            set { this._pagination = value; }
        }
        
        private IList<ProductReview> _results;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ProductReview> Results
        {
            get { return this._results; }
            set { this._results = value; }
        }
        
        private Seo _seo;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Seo Seo
        {
            get { return this._seo; }
            set { this._seo = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ProductReviewList class.
        /// </summary>
        public ProductReviewList()
        {
            this.Results = new LazyList<ProductReview>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken averageValue = inputObject["average"];
                if (averageValue != null && averageValue.Type != JTokenType.Null)
                {
                    this.Average = ((double)averageValue);
                }
                JToken countValue = inputObject["count"];
                if (countValue != null && countValue.Type != JTokenType.Null)
                {
                    this.Count = ((int)countValue);
                }
                JToken paginationValue = inputObject["pagination"];
                if (paginationValue != null && paginationValue.Type != JTokenType.Null)
                {
                    Pagination pagination = new Pagination();
                    pagination.DeserializeJson(paginationValue);
                    this.Pagination = pagination;
                }
                JToken resultsSequence = ((JToken)inputObject["results"]);
                if (resultsSequence != null && resultsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken resultsValue in ((JArray)resultsSequence))
                    {
                        ProductReview productReview = new ProductReview();
                        productReview.DeserializeJson(resultsValue);
                        this.Results.Add(productReview);
                    }
                }
                JToken seoValue = inputObject["seo"];
                if (seoValue != null && seoValue.Type != JTokenType.Null)
                {
                    Seo seo = new Seo();
                    seo.DeserializeJson(seoValue);
                    this.Seo = seo;
                }
            }
        }
    }
}
