// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ZtherApiIntegration.API.Models
{
    public partial class ProductReviewCreate
    {
        private string _comments;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Comments
        {
            get { return this._comments; }
            set { this._comments = value; }
        }
        
        private DateTimeOffset _entryDate;
        
        /// <summary>
        /// Required.
        /// </summary>
        public DateTimeOffset EntryDate
        {
            get { return this._entryDate; }
            set { this._entryDate = value; }
        }
        
        private string _firstName;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string FirstName
        {
            get { return this._firstName; }
            set { this._firstName = value; }
        }
        
        private string _lastName;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string LastName
        {
            get { return this._lastName; }
            set { this._lastName = value; }
        }
        
        private string _productCode;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string ProductCode
        {
            get { return this._productCode; }
            set { this._productCode = value; }
        }
        
        private int _rating;
        
        /// <summary>
        /// Required.
        /// </summary>
        public int Rating
        {
            get { return this._rating; }
            set { this._rating = value; }
        }

        /// Landau: Added Title, Location and Email.

        private string _title;

        /// <summary>
        /// Required.
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }

        private string _location;

        /// <summary>
        /// Required.
        /// </summary>
        public string Location
        {
            get { return this._location; }
            set { this._location = value; }
        }

        private string _email;

        /// <summary>
        /// Required.
        /// </summary>
        public string Email
        {
            get { return this._email; }
            set { this._email = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ProductReviewCreate class.
        /// </summary>
        public ProductReviewCreate()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ProductReviewCreate
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Comments == null)
            {
                throw new ArgumentNullException("Comments");
            }
            if (this.FirstName == null)
            {
                throw new ArgumentNullException("FirstName");
            }
            if (this.LastName == null)
            {
                throw new ArgumentNullException("LastName");
            }
            if (this.ProductCode == null)
            {
                throw new ArgumentNullException("ProductCode");
            }
            /// Landau: Added Title, Location and Email.
            if (this.Title == null)
            {
                throw new ArgumentNullException("Title");
            }
            if (this.Location == null)
            {
                throw new ArgumentNullException("Location");
            }
            if (this.Email == null)
            {
                throw new ArgumentNullException("Email");
            }
            if (this.Comments != null)
            {
                outputObject["comments"] = this.Comments;
            }
            outputObject["entryDate"] = this.EntryDate;
            if (this.FirstName != null)
            {
                outputObject["firstName"] = this.FirstName;
            }
            if (this.LastName != null)
            {
                outputObject["lastName"] = this.LastName;
            }
            if (this.ProductCode != null)
            {
                outputObject["productCode"] = this.ProductCode;
            }
            /// Landau: Added Title, Location and Email.
            if (this.Title != null)
            {
                outputObject["title"] = this.Title;
            }
            if (this.Location != null)
            {
                outputObject["location"] = this.Location;
            }
            if (this.Email != null)
            {
                outputObject["email"] = this.Email;
            }
            outputObject["rating"] = this.Rating;
            return outputObject;
        }
    }
}
