// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ZtherApiIntegration.API.Models
{
    public partial class ProductUpdate
    {
        private bool? _isNew;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsNew
        {
            get { return this._isNew; }
            set { this._isNew = value; }
        }
        
        private bool? _isPopular;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsPopular
        {
            get { return this._isPopular; }
            set { this._isPopular = value; }
        }
        
        private string _metaDescription;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string MetaDescription
        {
            get { return this._metaDescription; }
            set { this._metaDescription = value; }
        }
        
        private string _metaTitle;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string MetaTitle
        {
            get { return this._metaTitle; }
            set { this._metaTitle = value; }
        }
        
        private string _productCode;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string ProductCode
        {
            get { return this._productCode; }
            set { this._productCode = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ProductUpdate class.
        /// </summary>
        public ProductUpdate()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the ProductUpdate class with required
        /// arguments.
        /// </summary>
        public ProductUpdate(string productCode)
            : this()
        {
            if (productCode == null)
            {
                throw new ArgumentNullException("productCode");
            }
            this.ProductCode = productCode;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ProductUpdate
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.ProductCode == null)
            {
                throw new ArgumentNullException("ProductCode");
            }
            if (this.IsNew != null)
            {
                outputObject["isNew"] = this.IsNew.Value;
            }
            if (this.IsPopular != null)
            {
                outputObject["isPopular"] = this.IsPopular.Value;
            }
            if (this.MetaDescription != null)
            {
                outputObject["metaDescription"] = this.MetaDescription;
            }
            if (this.MetaTitle != null)
            {
                outputObject["metaTitle"] = this.MetaTitle;
            }
            if (this.ProductCode != null)
            {
                outputObject["productCode"] = this.ProductCode;
            }
            return outputObject;
        }
    }
}
