// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ZtherApiIntegration.API.Models
{
    public partial class Size
    {
        private string _sizeCategory;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SizeCategory
        {
            get { return this._sizeCategory; }
            set { this._sizeCategory = value; }
        }
        
        private string _sizeCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SizeCode
        {
            get { return this._sizeCode; }
            set { this._sizeCode = value; }
        }
        
        private int? _sortOrder;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? SortOrder
        {
            get { return this._sortOrder; }
            set { this._sortOrder = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Size class.
        /// </summary>
        public Size()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken sizeCategoryValue = inputObject["sizeCategory"];
                if (sizeCategoryValue != null && sizeCategoryValue.Type != JTokenType.Null)
                {
                    this.SizeCategory = ((string)sizeCategoryValue);
                }
                JToken sizeCodeValue = inputObject["sizeCode"];
                if (sizeCodeValue != null && sizeCodeValue.Type != JTokenType.Null)
                {
                    this.SizeCode = ((string)sizeCodeValue);
                }
                JToken sortOrderValue = inputObject["sortOrder"];
                if (sortOrderValue != null && sortOrderValue.Type != JTokenType.Null)
                {
                    this.SortOrder = ((int)sortOrderValue);
                }
            }
        }
    }
}
